import type { CrawlVerdict } from './types';

/**
 * GENERATED FILE — do not edit by hand. Regenerate with `npm run audit:robots`.
 *
 * A sweep of Thai government and state-enterprise domains from a single audit
 * host. For each domain we request /robots.txt and / with a full desktop-Chrome
 * request profile — the client hints, fetch-metadata and Accept headers a real
 * browser sends, not merely a Chrome user-agent string, because WAFs fingerprint
 * the whole request — and then / again with Googlebot's user-agent.
 *
 * Any host that leaves refused or unreachable is then re-probed with headless
 * Chromium, which runs the challenge JavaScript, presents a browser's TLS
 * fingerprint, and names the exact network failure. Where it gets in, robots.txt
 * is read over that same connection, so the verdict rests on the file rather
 * than on what curl was allowed to see. `chromeStatus` records that stage.
 *
 * Verdicts are deliberately conservative:
 *   'blocked'     robots.txt itself disallows everything for Googlebot. This is
 *                 authoritative: the file is public and identical for everyone.
 *   'waf-blocked' both a full browser request profile and headless Chromium were
 *                 refused outright. NOT proof that the genuine Googlebot is too.
 *   'partial'     some paths disallowed; or a Cloudflare JavaScript challenge,
 *                 which real browsers and verified crawlers pass while archivers
 *                 and AI assistants do not; or a 403 shown only to a
 *                 self-declared Googlebot while a browser is served normally; or
 *                 a site that answers a real browser and nothing else.
 *   'unknown'     no connection at all, with the failure named by `kind`.
 */
export type AuditKind =
	| 'robots-disallow-all'
	| 'googlebot-exception'
	| 'js-challenge'
	| 'waf-rule'
	| 'origin-403'
	| 'ua-spoof-guard'
	| 'redirect-loop'
	| 'browser-only'
	| 'tls-invalid'
	| 'http-only'
	| 'no-robots'
	| 'html-not-robots'
	| 'dns-failure'
	| 'connection-failed'
	| 'server-error'
	| 'unreachable'
	| 'partial'
	| 'allowed';

export interface AuditRow {
	host: string;
	verdict: CrawlVerdict;
	kind: AuditKind;
	/** HTTP status for /robots.txt with a browser profile, redirects followed. */
	robotsStatus: number | null;
	/** HTTP status for / with Googlebot's user-agent. */
	homeStatus: number | null;
	/** HTTP status for / with a full desktop-Chrome request profile. */
	browserStatus: number | null;
	/** HTTP status headless Chromium got for /, or null if that stage was not needed. */
	chromeStatus: number | null;
	/** True when robots.txt carries a Googlebot-specific group overriding `*`. */
	googlebotRule: boolean;
	snippet: string;
}

export const AUDIT_DATE = '2026-08-28';
export const AUDIT_ROWS: AuditRow[] = [
	{ host: 'data.tmd.go.th', verdict: 'blocked', kind: 'robots-disallow-all', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow: /maps/\nDisallow: /satellite/\nDisallow: /radar/\nDisallow: /\nDisallow: /iws13' },
	{ host: 'process3.gprocurement.go.th', verdict: 'blocked', kind: 'robots-disallow-all', robotsStatus: 200, homeStatus: null, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow: /' },
	{ host: 'www.doeb.go.th', verdict: 'blocked', kind: 'robots-disallow-all', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow: /' },
	{ host: 'www.excise.go.th', verdict: 'blocked', kind: 'robots-disallow-all', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow: /' },
	{ host: 'www.gprocurement.go.th', verdict: 'blocked', kind: 'robots-disallow-all', robotsStatus: 200, homeStatus: null, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow: /' },
	{ host: 'epit.rd.go.th', verdict: 'waf-blocked', kind: 'origin-403', robotsStatus: 404, homeStatus: 403, browserStatus: 403, chromeStatus: 403, googlebotRule: false, snippet: 'Full desktop-Chrome request profile\n  GET /  ->  403  (origin refused (server: Apache/2.2.15 (CentOS)))\nGooglebot user-agent\n  GET /  ->  403\nGET /robots.txt  ->  404\n\nHeadless Chromium (real browser engine)\n  GET /  ->  403  (refused: 403 Forbidden)' },
	{ host: 'ipthailand.go.th', verdict: 'waf-blocked', kind: 'waf-rule', robotsStatus: 200, homeStatus: 403, browserStatus: 403, chromeStatus: 200, googlebotRule: false, snippet: 'Full desktop-Chrome request profile\n  GET /  ->  403  (Cloudflare managed challenge (JavaScript interstitial))\nGooglebot user-agent\n  GET /  ->  403\nGET /robots.txt  ->  200\n\nHeadless Chromium (real browser engine)\n  GET /  ->  200  (refused: Imperva / Incapsula block page)' },
	{ host: 'landsmaps.dol.go.th', verdict: 'waf-blocked', kind: 'waf-rule', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: 200, googlebotRule: false, snippet: 'GET /robots.txt  ->  200, but the body is a block page\n(Imperva / Incapsula interstitial served with a 200 status)\n\nHeadless Chromium (real browser engine)\n  GET /  ->  200  (refused: Imperva / Incapsula block page)' },
	{ host: 'www.culture.go.th', verdict: 'waf-blocked', kind: 'waf-rule', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: 200, googlebotRule: false, snippet: 'GET /robots.txt  ->  200, but the body is a block page\n(Imperva / Incapsula interstitial served with a 200 status)\n\nHeadless Chromium (real browser engine)\n  GET /  ->  200  (served normally)\n  GET /robots.txt  ->  200' },
	{ host: 'www.diw.go.th', verdict: 'waf-blocked', kind: 'waf-rule', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: 200, googlebotRule: false, snippet: 'GET /robots.txt  ->  200, but the body is a block page\n(Imperva / Incapsula interstitial served with a 200 status)\n\nHeadless Chromium (real browser engine)\n  GET /  ->  200  (refused: Imperva / Incapsula block page)' },
	{ host: 'www.dld.go.th', verdict: 'waf-blocked', kind: 'waf-rule', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: 200, googlebotRule: false, snippet: 'GET /robots.txt  ->  200, but the body is a block page\n(Imperva / Incapsula interstitial served with a 200 status)\n\nHeadless Chromium (real browser engine)\n  GET /  ->  200  (refused: Imperva / Incapsula block page)' },
	{ host: 'www.dnp.go.th', verdict: 'waf-blocked', kind: 'waf-rule', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: 200, googlebotRule: false, snippet: 'GET /robots.txt  ->  200, but the body is a block page\n(Imperva / Incapsula interstitial served with a 200 status)\n\nHeadless Chromium (real browser engine)\n  GET /  ->  200  (refused: Imperva / Incapsula block page)' },
	{ host: 'www.dpe.go.th', verdict: 'waf-blocked', kind: 'waf-rule', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: 200, googlebotRule: false, snippet: 'GET /robots.txt  ->  200, but the body is a block page\n(Imperva / Incapsula interstitial served with a 200 status)\n\nHeadless Chromium (real browser engine)\n  GET /  ->  200  (refused: Imperva / Incapsula block page)' },
	{ host: 'www.dsdw.go.th', verdict: 'waf-blocked', kind: 'origin-403', robotsStatus: 404, homeStatus: 403, browserStatus: 403, chromeStatus: 403, googlebotRule: false, snippet: 'Full desktop-Chrome request profile\n  GET /  ->  403  (origin refused (server: Microsoft-IIS/10.0))\nGooglebot user-agent\n  GET /  ->  403\nGET /robots.txt  ->  404\n\nHeadless Chromium (real browser engine)\n  GET /  ->  403  (refused: Imperva / Incapsula block page)' },
	{ host: 'www.dwf.go.th', verdict: 'waf-blocked', kind: 'waf-rule', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: 200, googlebotRule: false, snippet: 'GET /robots.txt  ->  200, but the body is a block page\n(Imperva / Incapsula interstitial served with a 200 status)\n\nHeadless Chromium (real browser engine)\n  GET /  ->  200  (refused: Imperva / Incapsula block page)' },
	{ host: 'www.forest.go.th', verdict: 'waf-blocked', kind: 'waf-rule', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: 200, googlebotRule: false, snippet: 'GET /robots.txt  ->  200, but the body is a block page\n(Imperva / Incapsula interstitial served with a 200 status)\n\nHeadless Chromium (real browser engine)\n  GET /  ->  200  (served normally)\n  GET /robots.txt  ->  200' },
	{ host: 'www.ipthailand.go.th', verdict: 'waf-blocked', kind: 'waf-rule', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: 200, googlebotRule: false, snippet: 'GET /robots.txt  ->  200, but the body is a block page\n(Imperva / Incapsula interstitial served with a 200 status)\n\nHeadless Chromium (real browser engine)\n  GET /  ->  200  (refused: Imperva / Incapsula block page)' },
	{ host: 'www.mof.go.th', verdict: 'waf-blocked', kind: 'waf-rule', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: 200, googlebotRule: false, snippet: 'GET /robots.txt  ->  200, but the body is a block page\n(Imperva / Incapsula interstitial served with a 200 status)\n\nHeadless Chromium (real browser engine)\n  GET /  ->  200  (served normally)\n  GET /robots.txt  ->  200' },
	{ host: 'www.sec.or.th', verdict: 'waf-blocked', kind: 'origin-403', robotsStatus: 403, homeStatus: 403, browserStatus: 403, chromeStatus: 403, googlebotRule: false, snippet: 'Full desktop-Chrome request profile\n  GET /  ->  403  (origin refused the request)\nGooglebot user-agent\n  GET /  ->  403\nGET /robots.txt  ->  403\n\nHeadless Chromium (real browser engine)\n  GET /  ->  403  (refused: Block Response)' },
	{ host: 'www.stou.ac.th', verdict: 'waf-blocked', kind: 'waf-rule', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: 200, googlebotRule: false, snippet: 'GET /robots.txt  ->  200, but the body is a block page\n(Imperva / Incapsula interstitial served with a 200 status)\n\nHeadless Chromium (real browser engine)\n  GET /  ->  200  (refused: Imperva / Incapsula block page)' },
	{ host: 'www.tisi.go.th', verdict: 'waf-blocked', kind: 'waf-rule', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: 200, googlebotRule: false, snippet: 'GET /robots.txt  ->  200, but the body is a block page\n(Imperva / Incapsula interstitial served with a 200 status)\n\nHeadless Chromium (real browser engine)\n  GET /  ->  200  (served normally)\n  GET /robots.txt  ->  200' },
	{ host: 'datawarehouse.dbd.go.th', verdict: 'partial', kind: 'browser-only', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: 200, googlebotRule: false, snippet: 'Full desktop-Chrome request profile\n  GET /            ->  redirects to itself, still looping after 5 hops\n  GET /robots.txt  ->  same loop\nTypically a cookie or session challenge that a crawler cannot complete.\n\nHeadless Chromium (real browser engine)\n  GET /  ->  200  (served normally)\n  GET /robots.txt  ->  403' },
	{ host: 'drive.ditp.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: true, snippet: '# Begin robots.txt file\n#/-----------------------------------------------\\\n#| In single portal/domain situations, uncomment the sitmap line and enter domain name\n#\\-----------------------------------------------/\n#Sitemap: http://www.DomainNamehere.com/sitemap.aspx\n\n\nUser-agent: *\nDisallow: /admin/\nDisallow: /App_Brows' },
	{ host: 'eservice.ipthailand.go.th', verdict: 'partial', kind: 'js-challenge', robotsStatus: 200, homeStatus: 403, browserStatus: 403, chromeStatus: 200, googlebotRule: false, snippet: 'Full desktop-Chrome request profile\n  GET /  ->  403  (Cloudflare managed challenge (JavaScript interstitial))\nGooglebot user-agent\n  GET /  ->  403\nGET /robots.txt  ->  200\n\nHeadless Chromium (real browser engine)\n  GET /  ->  200  (served normally)\n  GET /robots.txt  ->  200\n\n# As a condition of accessing this website, you agree to abide by the following\n# content signals:\n\n# (a)  If a Content-Signal = yes, you may collect content for the corresponding\n#      use.\n# (b)  If a Content-Signal = no, you may not collect content for the\n#      corresponding use.\n# (c)  If the website operator do' },
	{ host: 'gfmis.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow: /wp-admin/\nAllow: /wp-admin/admin-ajax.php\n\nSitemap: https://newgfmisthai.gfmis.go.th/sitemap.xml\nSitemap: https://newgfmisthai.gfmis.go.th/sitemap.rss' },
	{ host: 'ratchakitcha.soc.go.th', verdict: 'partial', kind: 'js-challenge', robotsStatus: 403, homeStatus: 403, browserStatus: 403, chromeStatus: 403, googlebotRule: false, snippet: 'Full desktop-Chrome request profile\n  GET /  ->  403  (Cloudflare managed challenge (JavaScript interstitial))\nGooglebot user-agent\n  GET /  ->  403\nGET /robots.txt  ->  403\n\nHeadless Chromium (real browser engine)\n  GET /  ->  403  (still held at the Cloudflare challenge page after 20s)' },
	{ host: 'thaievisa.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: '# https://www.robotstxt.org/robotstxt.html\nUser-agent: *\nAllow: /\n\n# Private, auth-only areas — no SEO value, keep them out of the index\nDisallow: /dashboard\nDisallow: /applications\nDisallow: /apply-application\nDisallow: /edit-application\nDisallow: /application-detail' },
	{ host: 'www.ago.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow: /wp-admin/\nAllow: /wp-admin/admin-ajax.php\n\nSitemap: https://www.ago.go.th/wp-sitemap.xml\n\nUser-agent: *\nDisallow: /wp-content/uploads/wpo/wpo-plugins-tables-list.json' },
	{ host: 'www.amlo.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: '# If the Joomla site is installed within a folder such as at\n# e.g. www.example.com/joomla/ the robots.txt file MUST be\n# moved to the site root at e.g. www.example.com/robots.txt\n# AND the joomla folder name MUST be prefixed to the disallowed\n# path, e.g. the Disallow rule for the /administrator/ folder\n# MUST be chan' },
	{ host: 'www.audit.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: '#\n# robots.txt\n#\n# This file is to prevent the crawling and indexing of certain parts\n# of your site by web crawlers and spiders run by sites like Yahoo!\n# and Google. By telling these "robots" where not to go on your site,\n# you save bandwidth and server resources.\n#\n# This file will be ignored unless it is at the roo' },
	{ host: 'www.bb.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nAllow:/\nDisallow: /inc/\nSitemap: https://bb.go.th/sitemap.xml' },
	{ host: 'www.bot.or.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\n\nDisallow: /_layouts/\nDisallow: /_vti_bin/\nDisallow: /_catalogs/\n\n\n\nSitemap: http://www.bot.or.th/th.sitemap.xml\nSitemap: http://www.bot.or.th/en.sitemap.xml' },
	{ host: 'www.caat.or.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow: /wp-admin/\nDisallow: /?s=\nDisallow: /page/*/?s=\nDisallow: /search/\nAllow: /wp-admin/admin-ajax.php\n\nUser-agent: *\nDisallow: /wp-content/uploads/wpo/wpo-plugins-tables-list.json\n' },
	{ host: 'www.cdd.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow: /cache\nDisallow: /th/cache\nDisallow: /en/cache\nDisallow: /cms\nDisallow: /th/cms\nDisallow: /en/cms\nDisallow: /admin' },
	{ host: 'www.cgd.go.th', verdict: 'partial', kind: 'browser-only', robotsStatus: 403, homeStatus: 403, browserStatus: 403, chromeStatus: 200, googlebotRule: false, snippet: 'Full desktop-Chrome request profile\n  GET /  ->  403  (Cloudflare edge refusal)\nGooglebot user-agent\n  GET /  ->  403\nGET /robots.txt  ->  403\n\nHeadless Chromium (real browser engine)\n  GET /  ->  200  (served normally)\n  GET /robots.txt  ->  200\n\nUser-agent: *\nAllow: /cs\n \nSitemap: http://www.cgd.go.th/sitemap.xml' },
	{ host: 'www.chiangmai.go.th', verdict: 'partial', kind: 'tls-invalid', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: 200, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  200  (served normally)\n  (certificate rejected: ERR_CERT_COMMON_NAME_INVALID; retried with verification off)\n  GET /robots.txt  ->  404' },
	{ host: 'www.chonburi.go.th', verdict: 'partial', kind: 'js-challenge', robotsStatus: 403, homeStatus: 403, browserStatus: 403, chromeStatus: 403, googlebotRule: false, snippet: 'Full desktop-Chrome request profile\n  GET /  ->  403  (Cloudflare managed challenge (JavaScript interstitial))\nGooglebot user-agent\n  GET /  ->  403\nGET /robots.txt  ->  403\n\nHeadless Chromium (real browser engine)\n  GET /  ->  403  (still held at the Cloudflare challenge page after 20s)' },
	{ host: 'www.chula.ac.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: '# WordPress Security - Block sensitive areas\nUser-agent: *\nDisallow: /wp-admin/\nDisallow: /wp-login.php\nDisallow: /wp-includes/\nDisallow: /wp-content/plugins/\nDisallow: /wp-content/themes/\nDisallow: /wp-content/uploads/.*\\.php$\nDisallow: /wp-json/\nDisallow: /xmlrpc.php' },
	{ host: 'www.cmu.ac.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow: /Control\nDisallow: /Bin\nDisallow: /ResourceText' },
	{ host: 'www.coj.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\n\n\nDisallow: /admin/\nDisallow: /*.xls$\nDisallow: /plugins/ \nDisallow: /th/search/\nDisallow: /*.pdf$\nDisallow: /dist/\nDisallow: /th/cms/' },
	{ host: 'www.dep.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: '# If the Joomla site is installed within a folder\n# eg www.example.com/joomla/ then the robots.txt file\n# MUST be moved to the site root\n# eg www.example.com/robots.txt\n# AND the joomla folder name MUST be prefixed to all of the\n# paths.\n# eg the Disallow rule for the /administrator/ folder MUST\n# be changed to read\n# ' },
	{ host: 'www.dft.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: true, snippet: '# Begin robots.txt file\n#/-----------------------------------------------\\\n#| In single portal/domain situations, uncomment the sitmap line and enter domain name\n#\\-----------------------------------------------/\n#Sitemap: http://www.DomainNamehere.com/sitemap.aspx\n\n\nUser-agent: *\nDisallow: /admin/\nDisallow: /App_Brows' },
	{ host: 'www.dga.or.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow: /wp-admin/\nAllow: /wp-admin/admin-ajax.php\n\nSitemap: https://www.dga.or.th/sitemap_index.xml' },
	{ host: 'www.dip.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nAllow: /\nDisallow: /build\nDisallow: /bo\n\nSitemap: https://www.dip.go.th/th/sitemap' },
	{ host: 'www.ditp.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nAllow: /\nDisallow: /api/\nDisallow: /login\nDisallow: /draft-preview/\nDisallow: /e-survey-from/\nDisallow: /e-survey-export-readiness-assessment/\nDisallow: /e-survey-public-participation/\n\n# AI Search Engine Bots — Allow for AEO (Answer Engine Optimization)' },
	{ host: 'www.djop.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nAllow: /\n\nDisallow: /admin\nDisallow: /storage\n\nSitemap: https://www.djop.go.th/sitemap.xml' },
	{ host: 'www.dmr.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: '# This virtual robots.txt file was created by the Virtual Robots.txt WordPress plugin: https://www.wordpress.org/plugins/pc-robotstxt/\nUser-agent: *\nAllow: /\nDisallow: /wp-admin/\nAllow: /wp-admin/admin-ajax.php\nDisallow: /wp-includes/\nAllow: /wp-includes/js/\nAllow: /wp-includes/images/\nDisallow: /trackback/\nDisallow: /' },
	{ host: 'www.doa.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 403, homeStatus: 403, browserStatus: 403, chromeStatus: 200, googlebotRule: false, snippet: 'Full desktop-Chrome request profile\n  GET /  ->  403  (origin refused the request)\nGooglebot user-agent\n  GET /  ->  403\nGET /robots.txt  ->  403\n\nHeadless Chromium (real browser engine)\n  GET /  ->  200  (served normally)\n  GET /robots.txt  ->  200\n\nUser-agent: *\nDisallow: /wp-admin/\nDisallow: /wp-includes/\nDisallow: /wp-content/plugins/\nDisallow: /wp-content/themes/\nDisallow: /trackback/\nDisallow: /xmlrpc.php\nDisallow: /wp-login.php\nDisallow: /comments/feed/\nDisallow: /feed/' },
	{ host: 'www.doae.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow: /wp-admin/\nAllow: /wp-admin/admin-ajax.php\n\nSitemap: https://www.doae.go.th/wp-sitemap.xml' },
	{ host: 'www.dop.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow: /Android/\nDisallow: /covid-19/\nDisallow: /dist/\nDisallow: /ebook/thnews.php?*' },
	{ host: 'www.dopa.go.th', verdict: 'partial', kind: 'ua-spoof-guard', robotsStatus: 200, homeStatus: 403, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'Full desktop-Chrome request profile\n  GET /  ->  200  (served normally)\nGooglebot user-agent\n  GET /  ->  403  (refused)' },
	{ host: 'www.egat.co.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow: /uploads/\nDisallow: /home/wp-admin/\nDisallow: /home/wp-content/\nDisallow: /home/wp-includes/\n\nSitemap: https://www.egat.co.th/home/sitemap_index.xml' },
	{ host: 'www.eppo.go.th', verdict: 'partial', kind: 'ua-spoof-guard', robotsStatus: 200, homeStatus: 403, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'Full desktop-Chrome request profile\n  GET /  ->  200  (served normally)\nGooglebot user-agent\n  GET /  ->  403  (refused)' },
	{ host: 'www.exat.co.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 503, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow: /wp-admin/\nAllow: /wp-admin/admin-ajax.php\n\nSitemap: https://www.exat.co.th/wp-sitemap.xml' },
	{ host: 'www.fda.moph.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow: /media.php\nDisallow: /bch/data/' },
	{ host: 'www.forensic.police.go.th', verdict: 'partial', kind: 'partial', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: 200, googlebotRule: false, snippet: 'Full desktop-Chrome request profile\n  GET /            ->  redirects to itself, still looping after 5 hops\n  GET /robots.txt  ->  same loop\nTypically a cookie or session challenge that a crawler cannot complete.\n\nHeadless Chromium (real browser engine)\n  GET /  ->  200  (served normally)\n  GET /robots.txt  ->  200\n\nUser-agent: *\nAllow: /\nDisallow: /*/' },
	{ host: 'www.gfmis.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow: /wp-admin/\nAllow: /wp-admin/admin-ajax.php\n\nSitemap: https://newgfmisthai.gfmis.go.th/sitemap.xml\nSitemap: https://newgfmisthai.gfmis.go.th/sitemap.rss' },
	{ host: 'www.gsb.or.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow: /gsb-backoffice/\nAllow: /gsb-backoffice/admin-ajax.php\nSitemap: https://www.gsb.or.th/wp-sitemap.xml' },
	{ host: 'www.hii.or.th', verdict: 'partial', kind: 'googlebot-exception', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: true, snippet: 'User-agent: *\nDisallow: /\n\nUser-agent: Googlebot\nAllow: /\n\nUser-agent: Bingbot\nAllow: /' },
	{ host: 'www.hsri.or.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'text\nUser-agent: *\nDisallow: /storage/texteditor/pdf' },
	{ host: 'www.khonkaen.go.th', verdict: 'partial', kind: 'js-challenge', robotsStatus: 403, homeStatus: 403, browserStatus: 403, chromeStatus: 403, googlebotRule: false, snippet: 'Full desktop-Chrome request profile\n  GET /  ->  403  (Cloudflare managed challenge (JavaScript interstitial))\nGooglebot user-agent\n  GET /  ->  403\nGET /robots.txt  ->  403\n\nHeadless Chromium (real browser engine)\n  GET /  ->  403  (still held at the Cloudflare challenge page after 20s)' },
	{ host: 'www.kmutt.ac.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: true, snippet: 'User-agent: *\n#Disallow: /\n\n## only google \nUser-agent: Googlebot\nUser-agent: Googlebot-Image\nUser-agent: AdsBot-Google\nUser-agent: AdsBot-Google-Mobile\nUser-agent: bingbot\nUser-agent: Google Page Speed Insights' },
	{ host: 'www.krisdika.go.th', verdict: 'partial', kind: 'tls-invalid', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: 404, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  404  (served normally)\n  (certificate rejected: ERR_CERT_COMMON_NAME_INVALID; retried with verification off)\n  GET /robots.txt  ->  404' },
	{ host: 'www.krungthai.com', verdict: 'partial', kind: 'partial', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: 200, googlebotRule: false, snippet: 'Full desktop-Chrome request profile\n  GET /            ->  redirects to itself, still looping after 5 hops\n  GET /robots.txt  ->  same loop\nTypically a cookie or session challenge that a crawler cannot complete.\n\nHeadless Chromium (real browser engine)\n  GET /  ->  200  (served normally)\n  GET /robots.txt  ->  200\n\nUser-agent: *\nDisallow: /Error\nDisallow: /dist\nDisallow: /Download/aboutKTB\nDisallow: /Download/news\nDisallow: /Download/generalcontent\nDisallow: /Download/download\nDisallow: /Download/economyresources\nDisallow: *.doc\nDisallow: *.xls' },
	{ host: 'www.ktb.co.th', verdict: 'partial', kind: 'partial', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: 200, googlebotRule: false, snippet: 'Full desktop-Chrome request profile\n  GET /            ->  redirects to itself, still looping after 5 hops\n  GET /robots.txt  ->  same loop\nTypically a cookie or session challenge that a crawler cannot complete.\n\nHeadless Chromium (real browser engine)\n  GET /  ->  200  (served normally)\n  GET /robots.txt  ->  200\n\nUser-agent: *\nDisallow: /Error\nDisallow: /dist\nDisallow: /Download/aboutKTB\nDisallow: /Download/news\nDisallow: /Download/generalcontent\nDisallow: /Download/download\nDisallow: /Download/economyresources\nDisallow: *.doc\nDisallow: *.xls' },
	{ host: 'www.labour.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: null, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: '# If the Joomla site is installed within a folder\n# eg www.example.com/joomla/ then the robots.txt file\n# MUST be moved to the site root\n# eg www.example.com/robots.txt\n# AND the joomla folder name MUST be prefixed to all of the\n# paths.\n# eg the Disallow rule for the /administrator/ folder MUST\n# be changed to read\n# ' },
	{ host: 'www.mahidol.ac.th', verdict: 'partial', kind: 'partial', robotsStatus: 403, homeStatus: 403, browserStatus: 403, chromeStatus: 200, googlebotRule: false, snippet: 'Full desktop-Chrome request profile\n  GET /  ->  403  (origin refused (server: AkamaiGHost))\nGooglebot user-agent\n  GET /  ->  403\nGET /robots.txt  ->  403\n\nHeadless Chromium (real browser engine)\n  GET /  ->  200  (served normally)\n  GET /robots.txt  ->  200\n\nUser-Agent: *\nDisallow: /?s=\nDisallow: /wp-admin/\nDisallow: /wp-content/plugins/\nDisallow: /muthai/\nDisallow: /mueng/\nDisallow: /panyaon/\nDisallow: /lib/\nDisallow: /mueng/news/news_2009_27.htm\nDisallow: /th/annual_report/2551/annual2551-11.pdf' },
	{ host: 'www.md.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: null, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow: /wp-includes/\nDisallow: /wp-content/plugins/\nDisallow: /wp-content/themes/\n\nAllow: /wp-content/uploads/\n\nSitemap: https://md.go.th/sitemap.xml' },
	{ host: 'www.mnre.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow: /upload\nDisallow: /weadmin\nDisallow: /webservice\nDisallow: /logs\nDisallow: /logs\nDisallow: /ckeditor\nDisallow: /fileman\nDisallow: /api\n' },
	{ host: 'www.moac.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow: /Admin\nDisallow: /uploads\nDisallow: /backup\nDisallow: /~jbloggs\nDisallow: /include \nDisallow: /system\nDisallow: /member\n\nSitemap: https://www.moac.go.th/video/index.php?action=sitemap' },
	{ host: 'www.moc.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow: /cache\nDisallow: /th/cache\nDisallow: /en/cache\nDisallow: /cms\nDisallow: /th/cms\nDisallow: /en/cms\nDisallow: /index.php\nDisallow: /th/index.php\nDisallow: /en/index.php' },
	{ host: 'www.mol.go.th', verdict: 'partial', kind: 'browser-only', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: 200, googlebotRule: false, snippet: 'GET /robots.txt  ->  200, but the body is a block page\n(Imperva / Incapsula interstitial served with a 200 status)\n\nHeadless Chromium (real browser engine)\n  GET /  ->  200  (served normally)\n  GET /robots.txt  ->  200' },
	{ host: 'www.moph.go.th', verdict: 'partial', kind: 'js-challenge', robotsStatus: 200, homeStatus: 403, browserStatus: 403, chromeStatus: 200, googlebotRule: false, snippet: 'Full desktop-Chrome request profile\n  GET /  ->  403  (Cloudflare managed challenge (JavaScript interstitial))\nGooglebot user-agent\n  GET /  ->  403\nGET /robots.txt  ->  200\n\nHeadless Chromium (real browser engine)\n  GET /  ->  200  (served normally)\n  GET /robots.txt  ->  200\n\n# As a condition of accessing this website, you agree to abide by the following\n# content signals:\n\n# (a)  If a Content-Signal = yes, you may collect content for the corresponding\n#      use.\n# (b)  If a Content-Signal = no, you may not collect content for the\n#      corresponding use.\n# (c)  If the website operator do' },
	{ host: 'www.nbtc.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 403, browserStatus: 403, chromeStatus: 200, googlebotRule: false, snippet: 'Full desktop-Chrome request profile\n  GET /  ->  403  (Cloudflare managed challenge (JavaScript interstitial))\nGooglebot user-agent\n  GET /  ->  403\nGET /robots.txt  ->  200\n\nHeadless Chromium (real browser engine)\n  GET /  ->  200  (served normally)\n  GET /robots.txt  ->  200\n\nUser-agent: *\nDisallow: /wps/contenthandler/' },
	{ host: 'www.nectec.or.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow: /wp-admin/\nAllow: /wp-admin/admin-ajax.php\n\nSitemap: https://www.nectec.or.th/sitemap_index.xml' },
	{ host: 'www.nesdc.go.th', verdict: 'partial', kind: 'partial', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: 200, googlebotRule: false, snippet: 'Full desktop-Chrome request profile\n  GET /            ->  redirects to itself, still looping after 5 hops\n  GET /robots.txt  ->  same loop\nTypically a cookie or session challenge that a crawler cannot complete.\n\nHeadless Chromium (real browser engine)\n  GET /  ->  200  (served normally)\n  GET /robots.txt  ->  200\n\nUser-agent: *\nDisallow: /wp-admin/\nAllow: /\nAllow: /wp-admin/admin-ajax.php\n\nSitemap: https://www.nesdc.go.th/sitemap_index.xml' },
	{ host: 'www.nhso.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: '# If the Joomla site is installed within a folder\n# eg www.example.com/joomla/ then the robots.txt file\n# MUST be moved to the site root\n# eg www.example.com/robots.txt\n# AND the joomla folder name MUST be prefixed to all of the\n# paths.\n# eg the Disallow rule for the /administrator/ folder MUST\n# be changed to read\n# ' },
	{ host: 'www.niets.or.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow: /assets/*\nDisallow: /forum/*\nDisallow: /uploads/*\nDisallow: /th/content/uploads/*\nDisallow: /en/content/uploads/*\nDisallow: /th/api/*\nDisallow: /en/api/*\n\nSitemap: https://www.niets.or.th/th/sitemap/xml' },
	{ host: 'www.nonthaburi.go.th', verdict: 'partial', kind: 'ua-spoof-guard', robotsStatus: 200, homeStatus: 403, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'Full desktop-Chrome request profile\n  GET /  ->  200  (served normally)\nGooglebot user-agent\n  GET /  ->  403  (refused)' },
	{ host: 'www.nstda.or.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nAllow: /\nDisallow: /procurement-archive/' },
	{ host: 'www.nu.ac.th', verdict: 'partial', kind: 'browser-only', robotsStatus: 403, homeStatus: 200, browserStatus: 403, chromeStatus: 200, googlebotRule: false, snippet: 'Full desktop-Chrome request profile\n  GET /  ->  403  (origin refused (server: nginx))\nGooglebot user-agent\n  GET /  ->  200\nGET /robots.txt  ->  403\n\nHeadless Chromium (real browser engine)\n  GET /  ->  200  (served normally)\n  GET /robots.txt  ->  404' },
	{ host: 'www.obec.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow: /wp-admin/\nAllow: /wp-admin/admin-ajax.php\n\nSitemap: https://www.obec.go.th/wp-sitemap.xml' },
	{ host: 'www.ocsc.go.th', verdict: 'partial', kind: 'js-challenge', robotsStatus: 200, homeStatus: 403, browserStatus: 403, chromeStatus: 200, googlebotRule: false, snippet: 'Full desktop-Chrome request profile\n  GET /  ->  403  (Cloudflare managed challenge (JavaScript interstitial))\nGooglebot user-agent\n  GET /  ->  403\nGET /robots.txt  ->  200\n\nHeadless Chromium (real browser engine)\n  GET /  ->  200  (served normally)\n  GET /robots.txt  ->  200\n\n# As a condition of accessing this website, you agree to abide by the following\n# content signals:\n\n# (a)  If a Content-Signal = yes, you may collect content for the corresponding\n#      use.\n# (b)  If a Content-Signal = no, you may not collect content for the\n#      corresponding use.\n# (c)  If the website operator do' },
	{ host: 'www.oncb.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: null, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: '# Group 1\nUser-agent: *\nDisallow: /manage' },
	{ host: 'www.onep.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow: /wp-admin/\nAllow: /wp-admin/admin-ajax.php\n\nSitemap: https://www.onep.go.th/wp-sitemap.xml\n\nUser-agent: *\nDisallow: /wp-content/uploads/wpo/wpo-plugins-tables-list.json' },
	{ host: 'www.opdc.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow: /wp-admin/\nAllow: /wp-admin/admin-ajax.php\n\nSitemap: https://www.opdc.go.th/sitemap_index.xml' },
	{ host: 'www.parliament.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: true, snippet: 'User-agent: Googlebot\nDisallow: /english/tnews.php\n\nUser-agent: *\nDisallow: /english/tnews.php\n\nSitemap: https://www.parliament.go.th/sitemap.xml' },
	{ host: 'www.pathumthani.go.th', verdict: 'partial', kind: 'js-challenge', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: 200, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  200  (still held at the Cloudflare challenge page after 20s)' },
	{ host: 'www.pcd.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: null, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow: /wp-admin/\nAllow: /wp-admin/admin-ajax.php' },
	{ host: 'www.psu.ac.th', verdict: 'partial', kind: 'browser-only', robotsStatus: 200, homeStatus: 403, browserStatus: 403, chromeStatus: 200, googlebotRule: false, snippet: 'Full desktop-Chrome request profile\n  GET /  ->  403  (Cloudflare edge refusal)\nGooglebot user-agent\n  GET /  ->  403\nGET /robots.txt  ->  200\n\nHeadless Chromium (real browser engine)\n  GET /  ->  200  (served normally)\n  GET /robots.txt  ->  200\n\nUser-agent: *\nSitemap: https://www.psu.ac.th/sitemap.xml\nUser-agent:Twitterbot\nDisallow:' },
	{ host: 'www.ratchaburi.go.th', verdict: 'partial', kind: 'ua-spoof-guard', robotsStatus: 403, homeStatus: 403, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'Full desktop-Chrome request profile\n  GET /  ->  200  (served normally)\nGooglebot user-agent\n  GET /  ->  403  (refused)' },
	{ host: 'www.ratchakitcha.soc.go.th', verdict: 'partial', kind: 'js-challenge', robotsStatus: 403, homeStatus: 403, browserStatus: 403, chromeStatus: 403, googlebotRule: false, snippet: 'Full desktop-Chrome request profile\n  GET /  ->  403  (Cloudflare managed challenge (JavaScript interstitial))\nGooglebot user-agent\n  GET /  ->  403\nGET /robots.txt  ->  403\n\nHeadless Chromium (real browser engine)\n  GET /  ->  403  (still held at the Cloudflare challenge page after 20s)' },
	{ host: 'www.rd.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nAllow: /\nDisallow: /typo3conf\nDisallow: /clustercontrol\nDisallow: /cmon' },
	{ host: 'www.samutprakan.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow: /wp-admin/\nAllow: /wp-admin/admin-ajax.php\n\nSitemap: https://www.samutprakan.go.th/wp-sitemap.xml' },
	{ host: 'www.sat.or.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow: /wp-admin/\nAllow: /wp-admin/admin-ajax.php\n\nSitemap: https://www.sat.or.th/wp-sitemap.xml' },
	{ host: 'www.senate.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow: /v2/\nDisallow: /document/\nDisallow: /webstatic/\nDisallow: /analytics/' },
	{ host: 'www.set.or.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nAllow:  /\nDisallow: /*/preview/\nDisallow: /preview/\nDisallow: /config/\nDisallow: /data/\nDisallow: /dat/\nDisallow: /_partial/\nDisallow: /commons/\nDisallow: /set/' },
	{ host: 'www.soc.go.th', verdict: 'partial', kind: 'js-challenge', robotsStatus: 403, homeStatus: 403, browserStatus: 403, chromeStatus: 403, googlebotRule: false, snippet: 'Full desktop-Chrome request profile\n  GET /  ->  403  (Cloudflare managed challenge (JavaScript interstitial))\nGooglebot user-agent\n  GET /  ->  403\nGET /robots.txt  ->  403\n\nHeadless Chromium (real browser engine)\n  GET /  ->  403  (still held at the Cloudflare challenge page after 20s)' },
	{ host: 'www.songkhla.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow: /\nAllow: /$\nAllow: /index.html$\nAllow: /index.php$\nAllow: /event.php$\nAllow: /intro$\nAllow: /frontpage$\nAllow: /activity$\nAllow: /activity_boss$' },
	{ host: 'www.tcc.or.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow: /wp-content/uploads/wpo/wpo-plugins-tables-list.json\n\n# START YOAST BLOCK\n# ---------------------------\nUser-agent: *\nDisallow:\n\nSitemap: https://www.tcc.or.th/sitemap_index.xml\n# ---------------------------' },
	{ host: 'www.thaiairways.com', verdict: 'partial', kind: 'partial', robotsStatus: 403, homeStatus: 200, browserStatus: 403, chromeStatus: 200, googlebotRule: false, snippet: 'Full desktop-Chrome request profile\n  GET /  ->  403  (origin refused (server: CloudFront))\nGooglebot user-agent\n  GET /  ->  200\nGET /robots.txt  ->  403\n\nHeadless Chromium (real browser engine)\n  GET /  ->  200  (served normally)\n  GET /robots.txt  ->  200\n\nUser-agent: *\nDisallow: /*_wcag/\nDisallow: /*_*_wcag/\nDisallow: /iw-cc/\nDisallow: /app/rop/api/\nDisallow: /app/corporate/\nDisallow: /thai_shop/\nDisallow: /about-thai/public-information/\nDisallow: /*/content/json/* \nDisallow: /*/checkin/*' },
	{ host: 'www.thaichamber.org', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: '# START nuxt-robots (indexable)\nUser-agent: *\nDisallow: /cms-map\nDisallow: /api/cms/\nDisallow: /api/submitGoogleSheet\nDisallow: /api/__sitemap__/\n\nSitemap: https://www.thaichamber.org/sitemap.xml\n# END nuxt-robots' },
	{ host: 'www.thaievisa.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: '# https://www.robotstxt.org/robotstxt.html\nUser-agent: *\nAllow: /\n\n# Private, auth-only areas — no SEO value, keep them out of the index\nDisallow: /dashboard\nDisallow: /applications\nDisallow: /apply-application\nDisallow: /edit-application\nDisallow: /application-detail' },
	{ host: 'www.tourismthailand.org', verdict: 'partial', kind: 'js-challenge', robotsStatus: 200, homeStatus: 403, browserStatus: 403, chromeStatus: 200, googlebotRule: false, snippet: 'Full desktop-Chrome request profile\n  GET /  ->  403  (Cloudflare managed challenge (JavaScript interstitial))\nGooglebot user-agent\n  GET /  ->  403\nGET /robots.txt  ->  200\n\nHeadless Chromium (real browser engine)\n  GET /  ->  200  (served normally)\n  GET /robots.txt  ->  200\n\n# As a condition of accessing this website, you agree to abide by the following\n# content signals:\n\n# (a)  If a Content-Signal = yes, you may collect content for the corresponding\n#      use.\n# (b)  If a Content-Signal = no, you may not collect content for the\n#      corresponding use.\n# (c)  If the website operator do' },
	{ host: 'www.tu.ac.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'Sitemap: https://tu.ac.th/sitemap.xml\nSitemap: https://tu.ac.th/news-sitemap.xml\nUser-agent: *\nDisallow: /wp/wp-admin/\nAllow: /wp/wp-admin/admin-ajax.php\n\n# START YOAST BLOCK\n# ---------------------------\nUser-agent: *\nDisallow:' },
	{ host: 'www.vec.go.th', verdict: 'partial', kind: 'partial', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow: /wp-admin/\nAllow: /wp-admin/admin-ajax.php\n\nSitemap: https://www.vec.go.th/wp-sitemap.xml' },
	{ host: 'efiling.dbd.go.th', verdict: 'none', kind: 'no-robots', robotsStatus: 404, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  HTTP 404 Not Found' },
	{ host: 'efiling.rd.go.th', verdict: 'none', kind: 'no-robots', robotsStatus: 404, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  HTTP 404 Not Found' },
	{ host: 'eservice.dlt.go.th', verdict: 'none', kind: 'html-not-robots', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  200, but an HTML page was served instead of a robots.txt' },
	{ host: 'eservice.dol.go.th', verdict: 'none', kind: 'html-not-robots', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  200, but an HTML page was served instead of a robots.txt' },
	{ host: 'eservice.nhso.go.th', verdict: 'none', kind: 'html-not-robots', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: 200, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  200  (served normally)\n  GET /robots.txt  ->  200' },
	{ host: 'eservice.rd.go.th', verdict: 'none', kind: 'no-robots', robotsStatus: 404, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  HTTP 404 Not Found' },
	{ host: 'etax.rd.go.th', verdict: 'none', kind: 'no-robots', robotsStatus: 404, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  HTTP 404 Not Found' },
	{ host: 'extranet.immigration.go.th', verdict: 'none', kind: 'no-robots', robotsStatus: 404, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  HTTP 404 Not Found' },
	{ host: 'meaeservice.mea.or.th', verdict: 'none', kind: 'no-robots', robotsStatus: null, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /  ->  200 (site reachable)\nGET /robots.txt  ->  no response' },
	{ host: 'privus.fda.moph.go.th', verdict: 'none', kind: 'html-not-robots', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  200, but an HTML page was served instead of a robots.txt' },
	{ host: 'smartjob.doe.go.th', verdict: 'none', kind: 'html-not-robots', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  200, but an HTML page was served instead of a robots.txt' },
	{ host: 'track.thailandpost.co.th', verdict: 'none', kind: 'html-not-robots', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  200, but an HTML page was served instead of a robots.txt' },
	{ host: 'water.rid.go.th', verdict: 'none', kind: 'no-robots', robotsStatus: 404, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  HTTP 404 Not Found' },
	{ host: 'www.baac.or.th', verdict: 'none', kind: 'no-robots', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /  ->  200 (site reachable)\nGET /robots.txt  ->  200' },
	{ host: 'www.bora.dopa.go.th', verdict: 'none', kind: 'no-robots', robotsStatus: 404, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  HTTP 404 Not Found' },
	{ host: 'www.bts.co.th', verdict: 'none', kind: 'no-robots', robotsStatus: 404, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  HTTP 404 Not Found' },
	{ host: 'www.consular.go.th', verdict: 'none', kind: 'no-robots', robotsStatus: 404, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  HTTP 404 Not Found' },
	{ host: 'www.customs.go.th', verdict: 'none', kind: 'no-robots', robotsStatus: 404, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  HTTP 404 Not Found' },
	{ host: 'www.dbd.go.th', verdict: 'none', kind: 'no-robots', robotsStatus: 404, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  HTTP 404 Not Found' },
	{ host: 'www.dcy.go.th', verdict: 'none', kind: 'no-robots', robotsStatus: 404, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  HTTP 404 Not Found' },
	{ host: 'www.dede.go.th', verdict: 'none', kind: 'no-robots', robotsStatus: 404, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  HTTP 404 Not Found' },
	{ host: 'www.disaster.go.th', verdict: 'none', kind: 'no-robots', robotsStatus: 404, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  HTTP 404 Not Found' },
	{ host: 'www.dla.go.th', verdict: 'none', kind: 'no-robots', robotsStatus: 404, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  HTTP 404 Not Found' },
	{ host: 'www.dlt.go.th', verdict: 'none', kind: 'no-robots', robotsStatus: 404, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  HTTP 404 Not Found' },
	{ host: 'www.doe.go.th', verdict: 'none', kind: 'no-robots', robotsStatus: 404, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  HTTP 404 Not Found' },
	{ host: 'www.drr.go.th', verdict: 'none', kind: 'no-robots', robotsStatus: 404, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  HTTP 404 Not Found' },
	{ host: 'www.dsi.go.th', verdict: 'none', kind: 'no-robots', robotsStatus: 404, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  HTTP 404 Not Found' },
	{ host: 'www.dwr.go.th', verdict: 'none', kind: 'no-robots', robotsStatus: 404, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  HTTP 404 Not Found' },
	{ host: 'www.ect.go.th', verdict: 'none', kind: 'html-not-robots', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  200, but an HTML page was served instead of a robots.txt' },
	{ host: 'www.etda.or.th', verdict: 'none', kind: 'html-not-robots', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  200, but an HTML page was served instead of a robots.txt' },
	{ host: 'www.exim.go.th', verdict: 'none', kind: 'no-robots', robotsStatus: 404, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  HTTP 404 Not Found' },
	{ host: 'www.fpo.go.th', verdict: 'none', kind: 'html-not-robots', robotsStatus: 500, homeStatus: 500, browserStatus: 500, chromeStatus: 200, googlebotRule: false, snippet: 'GET /robots.txt  ->  HTTP 500\n\nHeadless Chromium (real browser engine)\n  GET /  ->  200  (served normally)\n  GET /robots.txt  ->  200' },
	{ host: 'www.kku.ac.th', verdict: 'none', kind: 'http-only', robotsStatus: 403, homeStatus: 200, browserStatus: 403, chromeStatus: 200, googlebotRule: false, snippet: 'Full desktop-Chrome request profile\n  GET /  ->  403  (origin refused the request)\nGooglebot user-agent\n  GET /  ->  200\nGET /robots.txt  ->  403\n\nHeadless Chromium (real browser engine)\n  GET /  ->  200  (served normally)\n  (no working HTTPS: ERR_TIMED_OUT; served over plain http://)\n  GET /robots.txt  ->  200' },
	{ host: 'www.ku.ac.th', verdict: 'none', kind: 'html-not-robots', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  200, but an HTML page was served instead of a robots.txt' },
	{ host: 'www.ldd.go.th', verdict: 'none', kind: 'html-not-robots', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  200, but an HTML page was served instead of a robots.txt' },
	{ host: 'www.m-society.go.th', verdict: 'none', kind: 'no-robots', robotsStatus: 404, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  HTTP 404 Not Found' },
	{ host: 'www.mea.or.th', verdict: 'none', kind: 'no-robots', robotsStatus: null, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /  ->  200 (site reachable)\nGET /robots.txt  ->  no response' },
	{ host: 'www.mfa.go.th', verdict: 'none', kind: 'no-robots', robotsStatus: 404, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  HTTP 404 Not Found' },
	{ host: 'www.moj.go.th', verdict: 'none', kind: 'no-robots', robotsStatus: 404, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  HTTP 404 Not Found' },
	{ host: 'www.nso.go.th', verdict: 'none', kind: 'no-robots', robotsStatus: 418, homeStatus: 200, browserStatus: 418, chromeStatus: 200, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  200  (served normally)\n  GET /robots.txt  ->  404' },
	{ host: 'www.oae.go.th', verdict: 'none', kind: 'html-not-robots', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  200, but an HTML page was served instead of a robots.txt' },
	{ host: 'www.ombudsman.go.th', verdict: 'none', kind: 'no-robots', robotsStatus: 404, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  HTTP 404 Not Found' },
	{ host: 'www.onwr.go.th', verdict: 'none', kind: 'no-robots', robotsStatus: 404, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  HTTP 404 Not Found' },
	{ host: 'www.pdmo.go.th', verdict: 'none', kind: 'no-robots', robotsStatus: 404, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  HTTP 404 Not Found' },
	{ host: 'www.probation.go.th', verdict: 'none', kind: 'no-robots', robotsStatus: 404, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  HTTP 404 Not Found' },
	{ host: 'www.railway.co.th', verdict: 'none', kind: 'no-robots', robotsStatus: 404, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  HTTP 404 Not Found' },
	{ host: 'www.rid.go.th', verdict: 'none', kind: 'html-not-robots', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  200, but an HTML page was served instead of a robots.txt' },
	{ host: 'www.sso.go.th', verdict: 'none', kind: 'no-robots', robotsStatus: null, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /  ->  200 (site reachable)\nGET /robots.txt  ->  no response' },
	{ host: 'www.tmd.go.th', verdict: 'none', kind: 'no-robots', robotsStatus: 404, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  HTTP 404 Not Found' },
	{ host: 'citizen.info.go.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow:' },
	{ host: 'edi.dft.go.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow:\nSitemap: https://edi.dft.go.th/game/sitemap.xml' },
	{ host: 'student.mytcas.com', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: '# https://www.robotstxt.org/robotstxt.html\nUser-agent: *\nDisallow:' },
	{ host: 'tdac.immigration.go.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: '# As a condition of accessing this website, you agree to abide by the following\n# content signals:\n\n# (a)  If a Content-Signal = yes, you may collect content for the corresponding\n#      use.\n# (b)  If a Content-Signal = no, you may not collect content for the\n#      corresponding use.\n# (c)  If the website operator do' },
	{ host: 'tm30.immigration.go.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: '# As a condition of accessing this website, you agree to abide by the following\n# content signals:\n\n# (a)  If a Content-Signal = yes, you may collect content for the corresponding\n#      use.\n# (b)  If a Content-Signal = no, you may not collect content for the\n#      corresponding use.\n# (c)  If the website operator do' },
	{ host: 'www.airportthai.co.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: '# START YOAST BLOCK\n# ---------------------------\nUser-agent: *\nDisallow:\n\nSitemap: https://www.airportthai.co.th/sitemap_index.xml\n# ---------------------------\n# END YOAST BLOCK' },
	{ host: 'www.bangkok.go.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow:' },
	{ host: 'www.constitutionalcourt.or.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: true, snippet: 'User-agent: Googlebot\nDisallow:\n\nSitemap: https://www.constitutionalcourt.or.th/occ_web/video/sitemap-index.xml' },
	{ host: 'www.dgr.go.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow:' },
	{ host: 'www.dmcr.go.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: true, snippet: 'User-agent: *\nAllow: /\n\nUser-agent: bingbot\nDisallow: /search\nDisallow: /download/\nDisallow: /attachment/\n\nUser-agent: GPTBot\nDisallow: /' },
	{ host: 'www.doh.go.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow:' },
	{ host: 'www.dtn.go.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: '# As a condition of accessing this website, you agree to abide by the following\n# content signals:\n\n# (a)  If a Content-Signal = yes, you may collect content for the corresponding\n#      use.\n# (b)  If a Content-Signal = no, you may not collect content for the\n#      corresponding use.\n# (c)  If the website operator do' },
	{ host: 'www.egov.go.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow:' },
	{ host: 'www.energy.go.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 302, browserStatus: 302, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow:' },
	{ host: 'www.erc.or.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 302, browserStatus: 302, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow:' },
	{ host: 'www.finearts.go.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow:' },
	{ host: 'www.fisheries.go.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: true, snippet: 'User-agent: googlebot\nAllow:' },
	{ host: 'www.fti.or.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: '# *\nUser-agent: *\nAllow: /\n\n# Host\nHost: https://fti.or.th/\n\n# Sitemaps\nSitemap: https://fti.or.th/sitemap.xml' },
	{ host: 'www.immigration.go.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: '# As a condition of accessing this website, you agree to abide by the following\n# content signals:\n\n# (a)  If a Content-Signal = yes, you may collect content for the corresponding\n#      use.\n# (b)  If a Content-Signal = no, you may not collect content for the\n#      corresponding use.\n# (c)  If the website operator do' },
	{ host: 'www.industry.go.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 302, browserStatus: 302, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow:' },
	{ host: 'www.info.go.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow:' },
	{ host: 'www.led.go.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nAllow: /\nSitemap: https://www.led.go.th/sitemap.xml' },
	{ host: 'www.mdes.go.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow:' },
	{ host: 'www.moe.go.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: '# START YOAST BLOCK\n# ---------------------------\nUser-agent: *\nDisallow:\n\nSitemap: https://www.moe.go.th/sitemap_index.xml\n# ---------------------------\n# END YOAST BLOCK' },
	{ host: 'www.moi.go.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow:' },
	{ host: 'www.mots.go.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: '# As a condition of accessing this website, you agree to abide by the following\n# content signals:\n\n# (a)  If a Content-Signal = yes, you may collect content for the corresponding\n#      use.\n# (b)  If a Content-Signal = no, you may not collect content for the\n#      corresponding use.\n# (c)  If the website operator do' },
	{ host: 'www.mrta.co.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: '# As a condition of accessing this website, you agree to abide by the following\n# content signals:\n\n# (a)  If a Content-Signal = yes, you may collect content for the corresponding\n#      use.\n# (b)  If a Content-Signal = no, you may not collect content for the\n#      corresponding use.\n# (c)  If the website operator do' },
	{ host: 'www.mwa.co.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: '# START YOAST BLOCK\n# ---------------------------\nUser-agent: *\nAllow: /\n\n# ---------------------------\n# END YOAST BLOCK' },
	{ host: 'www.nacc.go.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: '# As a condition of accessing this website, you agree to abide by the following\n# content signals:\n\n# (a)  If a Content-Signal = yes, you may collect content for the corresponding\n#      use.\n# (b)  If a Content-Signal = no, you may not collect content for the\n#      corresponding use.\n# (c)  If the website operator do' },
	{ host: 'www.nlt.go.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow:' },
	{ host: 'www.onesqa.or.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: '# As a condition of accessing this website, you agree to abide by the following\n# content signals:\n\n# (a)  If a Content-Signal = yes, you may collect content for the corresponding\n#      use.\n# (b)  If a Content-Signal = no, you may not collect content for the\n#      corresponding use.\n# (c)  If the website operator do' },
	{ host: 'www.opm.go.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: '<script language="JavaScript" type="text/JavaScript">window.location=\'https://www.opm.go.th/th/opm/landingpage/8/Slide%20banner%201\';</script>' },
	{ host: 'www.pea.co.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: true, snippet: '#\n# robots.txt\n#\n# This file is to prevent the crawling and indexing of certain parts\n# of your site by web crawlers and spiders run by sites like Yahoo!\n# and Google. By telling these "robots" where not to go on your site,\n# you save bandwidth and server resources.\n#\n# This file will be ignored unless it is at the roo' },
	{ host: 'www.phuket.go.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: '# As a condition of accessing this website, you agree to abide by the following\n# content signals:\n\n# (a)  If a Content-Signal = yes, you may collect content for the corresponding\n#      use.\n# (b)  If a Content-Signal = no, you may not collect content for the\n#      corresponding use.\n# (c)  If the website operator do' },
	{ host: 'www.pttplc.com', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *' },
	{ host: 'www.rlpd.go.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nAllow: /' },
	{ host: 'www.rtp.go.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: '# As a condition of accessing this website, you agree to abide by the following\n# content signals:\n\n# (a)  If a content-signal = yes, you may collect content for the corresponding\n#      use.\n# (b)  If a content-signal = no, you may not collect content for the\n#      corresponding use.\n# (c)  If the website operator do' },
	{ host: 'www.ru.ac.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nAllow: /\n\nSitemap: https://www.ru.ac.th/th/sitemap.xml' },
	{ host: 'www.ryt9.com', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow:' },
	{ host: 'www.smebank.co.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: null, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: '# START YOAST BLOCK\n# ---------------------------\nUser-agent: *\nDisallow:\n\nSitemap: https://www.smebank.co.th/sitemap_index.xml\n# ---------------------------\n# END YOAST BLOCK' },
	{ host: 'www.tat.or.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-Agent: *\nAllow: /\n\nSitemap: https://www.tat.or.th/sitemap.xml' },
	{ host: 'www.thaihealth.or.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: true, snippet: '# As a condition of accessing this website, you agree to abide by the following\n# content signals:\n\n# (a)  If a Content-Signal = yes, you may collect content for the corresponding\n#      use.\n# (b)  If a Content-Signal = no, you may not collect content for the\n#      corresponding use.\n# (c)  If the website operator do' },
	{ host: 'www.thailandpost.co.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: null, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-Agent: *\nDisallow:\n\nsitemap: http://www.thailandpost.co.th/sitemap.xml' },
	{ host: 'www.thairath.co.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: '# Allow all user agents to access everything\nUser-agent: *\nDisallow:\n\n# Explicitly allow certain crawlers (grapeshot and ias_crawler) to access everything\nUser-agent: grapeshot\nDisallow:\n\nUser-agent: ias_crawler\nDisallow:' },
	{ host: 'www.thaiwater.net', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\n\nSitemap: https://www.thaiwater.net/sitemap.xml' },
	{ host: 'www.treasury.go.th', verdict: 'allowed', kind: 'allowed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'User-agent: *\nDisallow:' },
	{ host: 'biz.govchannel.go.th', verdict: 'unknown', kind: 'connection-failed', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_TIMED_OUT)' },
	{ host: 'dolwebsite.dol.go.th', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' },
	{ host: 'edriving.dlt.go.th', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' },
	{ host: 'egp.gprocurement.go.th', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' },
	{ host: 'elicense.dlt.go.th', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' },
	{ host: 'epassport.mfa.go.th', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' },
	{ host: 'eservice.boi.go.th', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' },
	{ host: 'eservice.cgd.go.th', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' },
	{ host: 'eservice.dbd.go.th', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' },
	{ host: 'eservice.doae.go.th', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' },
	{ host: 'eservice.doeb.go.th', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' },
	{ host: 'eservice.dopa.go.th', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' },
	{ host: 'eservice.excise.go.th', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' },
	{ host: 'eservice.fda.moph.go.th', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' },
	{ host: 'eservice.moph.go.th', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' },
	{ host: 'eservice.mwa.co.th', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' },
	{ host: 'eservices.sso.go.th', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' },
	{ host: 'etax.customs.go.th', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' },
	{ host: 'etax.excise.go.th', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' },
	{ host: 'h4u.moph.go.th', verdict: 'unknown', kind: 'server-error', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: 504, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  504  (the server\'s own error page, over plain http:// — no working HTTPS, past a certificate that does not validate)' },
	{ host: 'linkage.bora.dopa.go.th', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' },
	{ host: 'patentsearch.dip.go.th', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' },
	{ host: 'regcompanyservice.dbd.go.th', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' },
	{ host: 'statbbi.nso.go.th', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' },
	{ host: 'vat.rd.go.th', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' },
	{ host: 'www.boi.go.th', verdict: 'unknown', kind: 'connection-failed', robotsStatus: 200, homeStatus: 200, browserStatus: 200, chromeStatus: null, googlebotRule: false, snippet: 'GET /robots.txt  ->  200, but the body is a block page\n(Imperva / Incapsula interstitial served with a 200 status)\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_TIMED_OUT)' },
	{ host: 'www.correct.go.th', verdict: 'unknown', kind: 'connection-failed', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_TIMED_OUT)' },
	{ host: 'www.deqp.go.th', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' },
	{ host: 'www.eservice.rd.go.th', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' },
	{ host: 'www.gdx.go.th', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' },
	{ host: 'www.gh.bank', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' },
	{ host: 'www.govchannel.go.th', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' },
	{ host: 'www.gsb.co.th', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' },
	{ host: 'www.hdc.moph.go.th', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' },
	{ host: 'www.jla.go.th', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' },
	{ host: 'www.khonthai.com', verdict: 'unknown', kind: 'server-error', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: 504, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  504  (the server\'s own error page, over plain http:// — no working HTTPS, past a certificate that does not validate)' },
	{ host: 'www.landsmaps.dol.go.th', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' },
	{ host: 'www.most.go.th', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' },
	{ host: 'www.mua.go.th', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' },
	{ host: 'www.nhc.go.th', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' },
	{ host: 'www.nsdv.go.th', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' },
	{ host: 'www.oag.go.th', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' },
	{ host: 'www.tcas.or.th', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' },
	{ host: 'www.thaipost.co.th', verdict: 'unknown', kind: 'dns-failure', robotsStatus: null, homeStatus: null, browserStatus: null, chromeStatus: null, googlebotRule: false, snippet: 'No response from the audit host\n\nHeadless Chromium (real browser engine)\n  GET /  ->  no connection (ERR_NAME_NOT_RESOLVED)' }
];

export const AUDIT_COUNTS: Record<string, number> = {"blocked":5,"waf-blocked":16,"partial":85,"none":49,"allowed":46,"unknown":44};
export const AUDIT_KINDS: Record<string, number> = {"robots-disallow-all":5,"origin-403":3,"waf-rule":13,"browser-only":5,"partial":63,"js-challenge":10,"tls-invalid":2,"ua-spoof-guard":4,"googlebot-exception":1,"no-robots":35,"html-not-robots":13,"http-only":1,"allowed":46,"connection-failed":3,"dns-failure":39,"server-error":2};
export const AUDIT_TOTAL = 245;

export function auditByVerdict(verdict: CrawlVerdict): AuditRow[] {
	return AUDIT_ROWS.filter((r) => r.verdict === verdict);
}
export function auditByKind(kind: AuditKind): AuditRow[] {
	return AUDIT_ROWS.filter((r) => r.kind === kind);
}
export function auditFor(host: string): AuditRow | undefined {
	return AUDIT_ROWS.find((r) => r.host === host);
}
